export const initialSessions = [
  {
    id: 1,
    campaignName: "Campaign 1",
    sessionState: "Pending",
    currentProgress: "50%",
    sessionType: "Burn",
    sessionLastsFor: "1 hour",
    activeBots: 10,
  },
  {
    id: 2,
    campaignName: "Campaign 2",
    sessionState: "Start",
    currentProgress: "80%",
    sessionType: "Premium",
    sessionLastsFor: "2 hours",
    activeBots: 15,
  },
  {
    id: 3,
    campaignName: "Campaign 3",
    sessionState: "Started",
    currentProgress: "20%",
    sessionType: "Burn",
    sessionLastsFor: "45 minutes",
    activeBots: 5,
  },
  {
    id: 4,
    campaignName: "Campaign 4",
    sessionState: "Stop",
    currentProgress: "90%",
    sessionType: "Premium",
    sessionLastsFor: "3 hours",
    activeBots: 20,
  },
  {
    id: 5,
    campaignName: "Campaign 5",
    sessionState: "Finished",
    currentProgress: "100%",
    sessionType: "Burn",
    sessionLastsFor: "4 hours",
    activeBots: 12,
  },
  {
    id: 6,
    campaignName: "Campaign 6",
    sessionState: "Pending",
    currentProgress: "10%",
    sessionType: "Premium",
    sessionLastsFor: "30 minutes",
    activeBots: 8,
  },
  {
    id: 7,
    campaignName: "Campaign 7",
    sessionState: "Start",
    currentProgress: "60%",
    sessionType: "Burn",
    sessionLastsFor: "1.5 hours",
    activeBots: 18,
  },
];
